components:
  responses:
    DEFAULT_ERROR:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
      description: Default error response
    UNPROCESSABLE_ENTITY:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
      description: Unprocessable Entity
  schemas:
    Analogy:
      properties:
        a:
          type: string
        b:
          type: string
        c:
          type: string
        completions:
          items: {}
          type: array
        n:
          type: integer
      type: object
    Embedding:
      properties:
        embeddings_list:
          items:
            items:
              type: number
            type: array
          type: array
        n:
          type: integer
        words:
          items:
            type: string
          type: array
        words_list:
          items:
            type: string
          type: array
      type: object
    Error:
      properties:
        code:
          description: Error code
          type: integer
        errors:
          description: Errors
          type: object
        message:
          description: Error message
          type: string
        status:
          description: Error name
          type: string
      type: object
    Neighbours:
      properties:
        n:
          type: integer
        neighbours:
          items:
            items: {}
            type: array
          type: array
        words:
          items:
            type: string
          type: array
      type: object
    PaginationMetadata:
      properties:
        first_page:
          type: integer
        last_page:
          type: integer
        next_page:
          type: integer
        page:
          type: integer
        previous_page:
          type: integer
        total:
          type: integer
        total_pages:
          type: integer
      type: object
    Vector:
      properties:
        vector:
          items:
            type: number
          type: array
        word:
          type: string
      type: object
info:
  title: Word2Med API
  version: v1
openapi: 3.0.2
paths:
  /analogy:
    get:
      description: For words a, b, and c, get a list of n words d which complete the
        analogy "a is to b as c is to d"
      parameters:
      - in: query
        name: b
        required: false
        schema:
          type: string
      - in: query
        name: c
        required: false
        schema:
          type: string
      - in: query
        name: n
        required: false
        schema:
          type: integer
      - in: query
        name: a
        required: false
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Analogy'
          description: OK
        '422':
          $ref: '#/components/responses/UNPROCESSABLE_ENTITY'
        default:
          $ref: '#/components/responses/DEFAULT_ERROR'
      summary: Get completions to an analogy
      tags:
      - word2med
  /embeddings:
    get:
      description: For the list of words, return a 2-dimensional embedding for each
        word and its neighbouring words.
      parameters:
      - explode: true
        in: query
        name: words
        required: false
        schema:
          items:
            type: string
          type: array
        style: form
      - in: query
        name: n
        required: false
        schema:
          type: integer
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Embedding'
          description: OK
        '422':
          $ref: '#/components/responses/UNPROCESSABLE_ENTITY'
        default:
          $ref: '#/components/responses/DEFAULT_ERROR'
      summary: Get the embeddings of words and their neighbours
      tags:
      - word2med
  /neighbours:
    get:
      description: For each input word, a list of the n closest words is returned,
        with the closest coming first.
      parameters:
      - explode: true
        in: query
        name: words
        required: false
        schema:
          items:
            type: string
          type: array
        style: form
      - in: query
        name: n
        required: false
        schema:
          type: integer
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Neighbours'
          description: OK
        '422':
          $ref: '#/components/responses/UNPROCESSABLE_ENTITY'
        default:
          $ref: '#/components/responses/DEFAULT_ERROR'
      summary: From a list of words, get the most similar words to each of them
      tags:
      - word2med
  /vector:
    get:
      parameters:
      - in: query
        name: word
        required: true
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Vector'
          description: OK
        '422':
          $ref: '#/components/responses/UNPROCESSABLE_ENTITY'
        default:
          $ref: '#/components/responses/DEFAULT_ERROR'
      summary: Get the vector representation of a word
      tags:
      - word2med
tags:
- description: Perform actions against the Word2Med model
  name: word2med
